Add WrapWithContext and ErrorWithContext functions
palantir/witchcraft-go-error pull request #33
Opened 2020-02-10 18:54 UTC by k-simons

## Before this PR

## After this PR
==COMMIT_MSG==

==COMMIT_MSG==

## Possible downsides?

2020-02-10 20:59 UTC, nmiyake commented
Thanks for the PR!

Yes, I believe I'm in sync with this at a high level -- I think the most common case is that we do want to include context params in errors, and the previous pattern for doing this (explicitly adding parameters from context as part of every error) has not been great. Also like that, since this introduces a new function, the previous/existing calls will continue to work as-is (and existing calls that manually add in params from context can be migrated manually).

This part may be a bit of semantics, but I'm wondering if the old forms should be deprecated... If there's a scenario where the error doesn't want to use context params (or is created in a function that isn't provided a context as one of its arguments), then using the previous form would be correct. However, these scenarios may be such an edge case that the value of signaling that the context version is most likely the correct one to use may outweigh the nit of the fact that there may exist valid scenarios in which the "deprecated" version should be used.

2020-02-10 21:04 UTC, k-simons commented
@nmiyake Yeah added the deprecation notice just as you mentioned to key developers into using the new version.

I could also introduce a new methods called `WrapWithoutContext` and `ErrorWithoutContext` that is basically the original behavior but un-deprecated. Would that be a middle ground?

2020-02-10 21:08 UTC, nmiyake commented
That would work around the deprecation, but my sense is that we probably don't have to go that far. Given that we don't anticipate this to be common, we can just leave it this way -- if there's some scenario where someone really wants the no context functionality and also really doesn't want to use a deprecated function, they can always pass `context.Background()` as the context (and if this is actually an issue we can always add these forms later). So, fine with just deprecating.

Will leave this comment in the PR as well, but in that case, would move most of the comments from the deprecated functions to the new ones -- I think it's a bit awkward for the documentation of the canonical versions to basically reference/refer to the documentation of deprecated functions.

2020-02-10 21:10 UTC, k-simons commented
@nmiyake Okay sounds good. Happy to iterate in CR for the rest of the PR

2020-02-11 01:13 UTC, k-simons commented
@nmiyake Okay addressed previous comments and added tests

2020-02-11 23:11 UTC, nmiyake requested changes
Thanks! Logic looks good, but feedback on naming, comments, and use of functions (would prefer deprecated to call new rather than the other way around)

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-:-M-qWEF28SUQu23wl9bE:b-1e3tl)* status: all files reviewed, 13 unresolved discussions (waiting on @k-simons)

___
*[werror.go, line 11 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qTSA5-s8AIUnc-AIK:-M-qQpE9AMknfbomj-60:brb6puq) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L11)):*
> ```Go
> )
> 
> // Error is identical to ErrorWithContext except it does move params from the context to the error
> ```

"does not". Suggested comment:

```
// Error is identical to calling ErrorWithContext with a context that does not have any wparams parameters.
// DEPRECATED: Please use ErrorWithContextParams instead to ensure that all the wparams parameters that are set on the
// context are included in the error.
```
___
*[werror.go, line 14 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qTZD8BLNuNVVGXXof:-M-qTZD8BLNuNVVGXXog:bntr9uy) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L14)):*
> ```Go
> // DEPRECATED: Please use ErrorWithContext instead to get full params
> func Error(msg string, params ...Param) error {
> 	return newWerror(msg, nil, params...)
> ```

Would prefer that we change this to call the non-deprecated function instead. That way, there are no internal references to the deprecated function and it makes the function easier to remove at a future time (and provides an example of how to work around the deprecation):

```
return ErrorWithContextParams(context.Background(), msg, params...)
```
___
*[werror.go, line 18 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qUuozCvlRPGQNiVEy:-M-qUuozCvlRPGQNiVEz:b-w7u074) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L18)):*
> ```Go
> 
> // ErrorWithContext returns a new error with the provided message and parameters
> // It also removes any stored params off the context and adds them to the error
> ```

Prefer not to use the term "removed" -- that gives the impression that the operation modifies the context, which it does not. Suggested content:

```
// ErrorWithContextParams returns a new error with the provided message and parameters. The returned error also includes any
// wparams parameters that are stored in the context.
```
___
*[werror.go, line 27 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qW2roBSfJAn7nqQdd:-M-qW2roBSfJAn7nqQde:b-pt8lho) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L27)):*
> ```Go
> //	password, ok := config["password"]
> //	if !ok {
> //		return werror.ErrorWithContext(ctx, "configuration is missing password")
> ```

If we change name of function (per suggestion below), this should be updated as well.
___
*[werror.go, line 30 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qV7dW9OE-K6SpFTr6:-M-qV7dW9OE-K6SpFTr7:b2qsuwq) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L30)):*
> ```Go
> //	}
> //
> func ErrorWithContext(ctx context.Context, msg string, params ...Param) error {
> ```

Can we name this `ErrorWithContextParams` instead? This makes it more explicit that the error has the params from the context -- otherwise, it sounds like the error has/contains the context itself.
___
*[werror.go, line 37 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVLEv6WKuZfeBv7yX:-M-qVLEv6WKuZfeBv7yY:bxe2huf) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L37)):*
> ```Go
> 	}
> 	fullParams = append(fullParams, params...)
> 	return Error(msg, fullParams...)
> ```

Change to `return newWerror(msg, nil, fullParams...)` so that it does not use deprecated function
___
*[werror.go, line 40 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVPBp-RZd7bl9Zh7F:-M-qVPBp-RZd7bl9Zh7G:bjp60aq) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L40)):*
> ```Go
> }
> 
> // Wrap is identical to WrapWithContext except it does move params from the context to the error
> ```

Similar comment to above. Suggested content:

```
// Wrap is identical to calling WrapWithContextParams with a context that does not have any wparams parameters.
// DEPRECATED: Please use WrapWithContextParams instead to ensure that all the wparams parameters that are set on the
// context are included in the error.
```
___
*[werror.go, line 43 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVWqk9rP-umldump8:-M-qVWqk9rP-umldump9:ba04h61) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L43)):*
> ```Go
> // DEPRECATED: Please use WrapWithContext instead to get full params
> func Wrap(err error, msg string, params ...Param) error {
> 	if err == nil {
> ```

Similar to above, would prefer to implement this in terms of new function -- recommendation:

```
return WrapWithContextParams(context.Background(), err, msg, params...)
```
___
*[werror.go, line 50 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVfCHB5KA36mvbqed:-M-qVfCHB5KA36mvbqee:b-bx4ycc) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L50)):*
> ```Go
> 
> // WrapWithContext returns a new error with the provided message and stores the provided error as its cause.
> // It also removes any stored params off the context and adds them to the error
> ```

Similar to above, prefer not to use "remove". Suggested:

```
// WrapWithContextParams returns a new error with the provided message and stores the provided error as its cause.
// The returned error also includes any wparams parameters that are stored in the context.
```
___
*[werror.go, line 59 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qW01vBga70YWEWJL1:-M-qW01w6OPr4JPl_dPG:b-pqmqf7) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L59)):*
> ```Go
> //	users, err := getUser(userID)
> //	if err != nil {
> //		return werror.Wrap(err, "failed to get user", werror.SafeParam("userId", userID))
> ```

Update example to use new function name
___
*[werror.go, line 62 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVkGG70NC4F_FbH9t:-M-qVkGG70NC4F_FbH9u:bnfudn5) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L62)):*
> ```Go
> //	}
> //
> func WrapWithContext(ctx context.Context, err error, msg string, params ...Param) error {
> ```

Similar to above, prefer `WrapWithContextParams`
___
*[werror.go, line 63 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVoRVDDYHEwW4aWn2:-M-qVoRVDDYHEwW4aWn3:b3hvncn) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L63)):*
> ```Go
> //
> func WrapWithContext(ctx context.Context, err error, msg string, params ...Param) error {
> 	safe, unsafe := wparams.SafeAndUnsafeParamsFromContext(ctx)
> ```

Would add the

```
if err == nil {
	return nil
}
```

as the first line of this function
___
*[werror.go, line 69 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVzAj5xe-InzdqXeI:-M-qVzAj5xe-InzdqXeJ:bxxcnhn) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L69)) [...]

2020-02-12 18:14 UTC, k-simons reviewed
Should be all done

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-:-M-uazK91B8_oY_YuI-b:b76pvbq)* status: all files reviewed, 13 unresolved discussions (waiting on @nmiyake)

___
*[werror.go, line 11 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qTSA5-s8AIUnc-AIK:-M-uXuADChHlAShQ-JMP:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L11)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

"does not". Suggested comment:

```
// Error is identical to calling ErrorWithContext with a context that does not have any wparams parameters.
// DEPRECATED: Please use ErrorWithContextParams instead to ensure that all the wparams parameters that are set on the
// context are included in the error.
```
</blockquote></details>

Done.
___
*[werror.go, line 14 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qTZD8BLNuNVVGXXof:-M-uYAs39TAcGXpmzXGf:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L14)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Would prefer that we change this to call the non-deprecated function instead. That way, there are no internal references to the deprecated function and it makes the function easier to remove at a future time (and provides an example of how to work around the deprecation):

```
return ErrorWithContextParams(context.Background(), msg, params...)
```
</blockquote></details>

Done.
___
*[werror.go, line 18 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qUuozCvlRPGQNiVEy:-M-uYCFR-30LnIr8Bg3D:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L18)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Prefer not to use the term "removed" -- that gives the impression that the operation modifies the context, which it does not. Suggested content:

```
// ErrorWithContextParams returns a new error with the provided message and parameters. The returned error also includes any
// wparams parameters that are stored in the context.
```
</blockquote></details>

Done.
___
*[werror.go, line 27 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qW2roBSfJAn7nqQdd:-M-uYCxp0PRQ8XBHuVC-:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L27)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

If we change name of function (per suggestion below), this should be updated as well.
</blockquote></details>

Done.
___
*[werror.go, line 30 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qV7dW9OE-K6SpFTr6:-M-uYEROB1kO88XwntTb:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L30)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Can we name this `ErrorWithContextParams` instead? This makes it more explicit that the error has the params from the context -- otherwise, it sounds like the error has/contains the context itself.
</blockquote></details>

Done.
___
*[werror.go, line 37 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVLEv6WKuZfeBv7yX:-M-uYG5r4b29niaT0ljC:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L37)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Change to `return newWerror(msg, nil, fullParams...)` so that it does not use deprecated function
</blockquote></details>

Done.
___
*[werror.go, line 40 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVPBp-RZd7bl9Zh7F:-M-uYVw69PqpOD7i_kXf:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L40)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Similar comment to above. Suggested content:

```
// Wrap is identical to calling WrapWithContextParams with a context that does not have any wparams parameters.
// DEPRECATED: Please use WrapWithContextParams instead to ensure that all the wparams parameters that are set on the
// context are included in the error.
```
</blockquote></details>

Done.
___
*[werror.go, line 43 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVWqk9rP-umldump8:-M-uYWJ50NW44NH9LSpv:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L43)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Similar to above, would prefer to implement this in terms of new function -- recommendation:

```
return WrapWithContextParams(context.Background(), err, msg, params...)
```
</blockquote></details>

Done.
___
*[werror.go, line 50 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVfCHB5KA36mvbqed:-M-uYYYV80oywNe-dGwV:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L50)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Similar to above, prefer not to use "remove". Suggested:

```
// WrapWithContextParams returns a new error with the provided message and stores the provided error as its cause.
// The returned error also includes any wparams parameters that are stored in the context.
```
</blockquote></details>

Done.
___
*[werror.go, line 59 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qW01vBga70YWEWJL1:-M-uYZCp5m36EequKrWk:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L59)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Update example to use new function name
</blockquote></details>

Done.
___
*[werror.go, line 62 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVkGG70NC4F_FbH9t:-M-uYZg40KaVh9saCwTE:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L62)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Similar to above, prefer `WrapWithContextParams`
</blockquote></details>

Done.
___
*[werror.go, line 63 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVoRVDDYHEwW4aWn2:-M-uY_Dl0Hbu9fnJna8-:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L63)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Would add the

```
if err == nil {
	return nil
}
```

as the first line of this function
</blockquote></details>

Done.
___
*[werror.go, line 69 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-M-qVzAj5xe-InzdqXeI:-M-uY_kU0PvEwgrej2eb:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-error/blob/44cf29d5b9f968b583ef3f06b9ed329488555bdc/werror.go#L69)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Change to `return newWerror(msg, err, fullParams...)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-12 19:35 UTC, nmiyake approved these changes
Thanks, <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-error/33#-:-M-utWl6CK1FS5Sr6mn4:bwq6wfm)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-02-12 19:35 UTC, merged

2020-02-12 19:37 UTC, nmiyake commented
Merged and released v1.3.0